# Generated by Django 5.0.1 on 2024-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_location_full_name_alter_location_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='name',
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
