# Generated by Django 5.0.1 on 2024-02-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_remove_screenshot_folder_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
