# Generated by Django 5.0.1 on 2024-02-12 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_screenshot_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='name',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='img_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='thmb_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
