# Generated by Django 5.0.1 on 2024-02-07 15:32

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_key',
            field=models.CharField(default=pyotp.random_base32, max_length=150),
        ),
    ]
